apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: backend-db-secrets
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "b18eeb32-8ecd-46e6-9bc3-21093b2988ac"
    keyvaultName: "logicmatrix-kv2026"
    tenantId: "32d8e066-ac9e-41cb-85f3-fdc3aeb9ea60"
    objects: |
      array:
        - |
          objectName: db-host
          objectType: secret
        - |
          objectName: db-name
          objectType: secret
        - |
          objectName: db-user
          objectType: secret
        - |
          objectName: db-password
          objectType: secret

  secretObjects:
    - secretName: backend-db-secret
      type: Opaque
      data:
        - objectName: db-host
          key: DB_HOST
        - objectName: db-name
          key: DB_NAME
        - objectName: db-user
          key: DB_USER
        - objectName: db-password
          key: DB_PASSWORD
